import moment from "moment";

import IEventModel from "./clubsHome/interfaces/IEventModel";

const socials = [
    "/static/instagram.svg",
    "/static/twitter.svg",
    "/static/youtube.svg",
    "/static/web.svg"
];

const tabs = [
    "Events",
    "Deals",
    "Reviews",
];

const reviewCards = [
    {
        name: "George",
        date: "28 Sep 2023",
        stars: 5,
        review:
            "I've seen amazing results in just a few weeks, and I feel stronger and healthier than ever before. The variety of workouts keeps things interesting, and the sense of community in the class is wonderful.",
    },
    {
        name: "Anna",
        date: "15 Sep 2023",
        stars: 4,
        review:
            "The workouts are well-structured, and I love how the trainers motivate you to push harder. Highly recommended!",
    },
    {
        name: "Michael",
        date: "10 Sep 2023",
        stars: 5,
        review:
            "Joining this program was one of the best decisions I’ve made. It’s changed my lifestyle for the better.",
    },
    {
        name: "Sophia",
        date: "5 Sep 2023",
        stars: 3,
        review:
            "The workouts are great, but I wish the class times were more flexible.",
    },
    ...Array.from({ length: 16 }, (_, index) => ({
        name: `User ${index + 5}`,
        date: "1 Sep 2023",
        stars: (index % 5) + 1,
        review: "Great experience with the program. Highly recommend it!",
    })),
].slice(0, 20);

const dummyEvents: IEventModel[] = [
    {
        type: "training",
        coverPhotoUrl: "/static/event.svg",
        optionalPhotos: [],
        sport: "Football",
        title: "Football Practice",
        description: "An exciting football practice session.",
        cancelled: false,
        deleted: false,
        participants: ["user1", "user2"],
        participantsLimit: 20,
        isUnlimitedParticipants: false,
        trainingLocationString: "Central Park",
        trainingLocation: { type: "Point", coordinates: [40.785091, -73.968285] },
        trainingStartDateTime: moment().add(2, "days").toISOString(),
        trainingEndDateTime: moment().add(2, "days").add(2, "hours").toISOString(),
        commentCount: 5,
        link: "https://example.com",
        likedBy: ["user1", "user3"],
        createdAt: moment().toISOString(),
        paymentMethods: ["credit card", "paypal"],
        price: 10,
        priceCurrency: "USD",
        clubId: "club1",
        otherPaymentMethod: "",
        creator: {
            uid: "creator1",
            userType: "coach",
            bio: "Experienced coach.",
            age: 35,
            email: "coach@example.com",
            isHidden: false,
            birthDate: "1988-01-15",
            coverPhoto: "/static/cover.jpg",
            mainProfilePhoto: "/static/profile.jpg",
            userPhotos: ["/static/photo1.jpg"],
            userInterests: ["football", "running"],
            name: "John Doe",
            gender: "Male",
            blockedUsers: [],
            joinedActivities: [],
            joinedEvents: [],
            joinedTrips: [],
            bookmarkedEvents: [],
            bookmarkedActivities: [],
            bookmarkedTrips: [],
            isProfileVerified: true,
            isEmailVerified: true,
            instagram: "coach_instagram",
            tikTok: "coach_tiktok",
            website: "https://coachwebsite.com",
            link: "https://coachprofile.com",
            youTube: "coach_youtube",
            fcmToken: ["token1", "token2"],
            reviewCount: 10,
            nationality: "American",
            nationalityCode: "US",
            connectedAccountId: "account123",
            createdAt: moment().toISOString(),
            lastSignedInAt: moment().toISOString(),
            createdLocation: { type: "Point", coordinates: [40.712776, -74.005974] },
            location: { type: "Point", coordinates: [40.712776, -74.005974] },
            locationString: "New York, USA",
            isNotificationsEnabled: true,
            isActivitiesNotificationsEnabled: true,
            isConnectionNotificationsEnabled: true,
            isMessageNotificationsEnabled: true,
        },
        isOnline: false,
    },
    {
        type: "match",
        coverPhotoUrl: "/static/event.svg",
        optionalPhotos: [],
        sport: "Basketball",
        title: "Basketball Practice",
        description: "Join us for a fun game of basketball in downtown LA.",
        cancelled: false,
        deleted: false,
        participants: ["user3", "user4"],
        participantsLimit: 10,
        isUnlimitedParticipants: false,
        trainingLocationString: "Downtown Gym",
        trainingLocation: { type: "Point", coordinates: [34.052235, -118.243683] },
        trainingStartDateTime: moment().add(5, "days").toISOString(),
        trainingEndDateTime: moment().add(5, "days").add(1.5, "hours").toISOString(),
        commentCount: 8,
        link: "https://basketballfun.com",
        likedBy: ["user1", "user4"],
        createdAt: moment().toISOString(),
        paymentMethods: ["cash"],
        price: 5,
        priceCurrency: "USD",
        clubId: "club2",
        otherPaymentMethod: "On-site payment",
        creator: {
            uid: "creator2",
            userType: "player",
            bio: "Loves basketball and community games.",
            age: 27,
            email: "player@example.com",
            isHidden: false,
            birthDate: "1996-04-18",
            coverPhoto: "/static/cover2.jpg",
            mainProfilePhoto: "/static/profile2.jpg",
            userPhotos: ["/static/photo2.jpg"],
            userInterests: ["basketball", "swimming"],
            name: "Jane Smith",
            gender: "Female",
            blockedUsers: [],
            joinedActivities: [],
            joinedEvents: [],
            joinedTrips: [],
            bookmarkedEvents: [],
            bookmarkedActivities: [],
            bookmarkedTrips: [],
            isProfileVerified: true,
            isEmailVerified: true,
            instagram: "basket_jane",
            tikTok: "",
            website: "",
            link: "https://janesmith.com",
            youTube: "",
            fcmToken: [],
            reviewCount: 7,
            nationality: "Canadian",
            nationalityCode: "CA",
            connectedAccountId: "account456",
            createdAt: moment().subtract(2, "days").toISOString(),
            lastSignedInAt: moment().toISOString(),
            createdLocation: { type: "Point", coordinates: [45.421532, -75.697189] },
            location: { type: "Point", coordinates: [45.421532, -75.697189] },
            locationString: "Ottawa, Canada",
            isNotificationsEnabled: true,
            isActivitiesNotificationsEnabled: true,
            isConnectionNotificationsEnabled: true,
            isMessageNotificationsEnabled: true,
        },
        isOnline: false,
    },
    {
        type: "match2",
        coverPhotoUrl: "/static/event.svg",
        optionalPhotos: [],
        sport: "Basketball",
        title: "Downtown Basketball Game",
        description: "Join us for a fun game of basketball in downtown LA.",
        cancelled: false,
        deleted: false,
        participants: ["user3", "user4"],
        participantsLimit: 10,
        isUnlimitedParticipants: false,
        trainingLocationString: "Downtown Gym",
        trainingLocation: { type: "Point", coordinates: [34.052235, -118.243683] },
        trainingStartDateTime: moment().add(5, "days").toISOString(),
        trainingEndDateTime: moment().add(5, "days").add(3, "hours").toISOString(),
        commentCount: 8,
        link: "https://basketballfun.com",
        likedBy: ["user1", "user4"],
        createdAt: moment().toISOString(),
        paymentMethods: ["cash"],
        price: 5,
        priceCurrency: "USD",
        clubId: "club2",
        otherPaymentMethod: "On-site payment",
        creator: {
            uid: "creator2",
            userType: "player",
            bio: "Loves basketball and community games.",
            age: 27,
            email: "player@example.com",
            isHidden: false,
            birthDate: "1996-04-18",
            coverPhoto: "/static/cover2.jpg",
            mainProfilePhoto: "/static/profile2.jpg",
            userPhotos: ["/static/photo2.jpg"],
            userInterests: ["basketball", "swimming"],
            name: "Jane Smith",
            gender: "Female",
            blockedUsers: [],
            joinedActivities: [],
            joinedEvents: [],
            joinedTrips: [],
            bookmarkedEvents: [],
            bookmarkedActivities: [],
            bookmarkedTrips: [],
            isProfileVerified: true,
            isEmailVerified: true,
            instagram: "basket_jane",
            tikTok: "",
            website: "",
            link: "https://janesmith.com",
            youTube: "",
            fcmToken: [],
            reviewCount: 7,
            nationality: "Canadian",
            nationalityCode: "CA",
            connectedAccountId: "account456",
            createdAt: moment().subtract(2, "days").toISOString(),
            lastSignedInAt: moment().toISOString(),
            createdLocation: { type: "Point", coordinates: [45.421532, -75.697189] },
            location: { type: "Point", coordinates: [45.421532, -75.697189] },
            locationString: "Ottawa, Canada",
            isNotificationsEnabled: true,
            isActivitiesNotificationsEnabled: true,
            isConnectionNotificationsEnabled: true,
            isMessageNotificationsEnabled: true,
        },
        isOnline: true,
    },
    {
        type: "match3",
        coverPhotoUrl: "/static/event.svg",
        optionalPhotos: [],
        sport: "Basketball",
        title: "Downtown Basketball Game",
        description: "Join us for a fun game of basketball in downtown LA.",
        cancelled: false,
        deleted: false,
        participants: ["user3", "user4"],
        participantsLimit: 10,
        isUnlimitedParticipants: false,
        trainingLocationString: "Downtown Gym",
        trainingLocation: { type: "Point", coordinates: [34.052235, -118.243683] },
        trainingStartDateTime: moment().add(8, "days").toISOString(),
        trainingEndDateTime: moment().add(8, "days").add(6, "hours").toISOString(),
        commentCount: 8,
        link: "https://basketballfun.com",
        likedBy: ["user1", "user4"],
        createdAt: moment().toISOString(),
        paymentMethods: ["cash"],
        price: 5,
        priceCurrency: "USD",
        clubId: "club2",
        otherPaymentMethod: "On-site payment",
        creator: {
            uid: "creator2",
            userType: "player",
            bio: "Loves basketball and community games.",
            age: 27,
            email: "player@example.com",
            isHidden: false,
            birthDate: "1996-04-18",
            coverPhoto: "/static/cover2.jpg",
            mainProfilePhoto: "/static/profile2.jpg",
            userPhotos: ["/static/photo2.jpg"],
            userInterests: ["basketball", "swimming"],
            name: "Jane Smith",
            gender: "Female",
            blockedUsers: [],
            joinedActivities: [],
            joinedEvents: [],
            joinedTrips: [],
            bookmarkedEvents: [],
            bookmarkedActivities: [],
            bookmarkedTrips: [],
            isProfileVerified: true,
            isEmailVerified: true,
            instagram: "basket_jane",
            tikTok: "",
            website: "",
            link: "https://janesmith.com",
            youTube: "",
            fcmToken: [],
            reviewCount: 7,
            nationality: "Canadian",
            nationalityCode: "CA",
            connectedAccountId: "account456",
            createdAt: moment().subtract(2, "days").toISOString(),
            lastSignedInAt: moment().toISOString(),
            createdLocation: { type: "Point", coordinates: [45.421532, -75.697189] },
            location: { type: "Point", coordinates: [45.421532, -75.697189] },
            locationString: "Ottawa, Canada",
            isNotificationsEnabled: true,
            isActivitiesNotificationsEnabled: true,
            isConnectionNotificationsEnabled: true,
            isMessageNotificationsEnabled: true,
        },
        isOnline: false,
    },
    {
        type: "tournament",
        coverPhotoUrl: "/static/event.svg",
        optionalPhotos: ["/static/tournament1.jpg"],
        sport: "Tennis",
        title: "Tennis Summer Open",
        description: "Join the exciting summer tennis tournament.",
        cancelled: false,
        deleted: false,
        participants: ["user7", "user8", "user9"],
        participantsLimit: 30,
        isUnlimitedParticipants: false,
        trainingLocationString: "Greenwood Tennis Club",
        trainingLocation: { type: "Point", coordinates: [51.5074, -0.1278] },
        trainingStartDateTime: moment().add(5, "days").toISOString(),
        trainingEndDateTime: moment().add(5, "days").add(1, "hours").toISOString(),
        commentCount: 15,
        link: "https://tennisopen.com",
        likedBy: ["user8", "user10"],
        createdAt: moment().subtract(3, "days").toISOString(),
        paymentMethods: ["credit card"],
        price: 20,
        priceCurrency: "GBP",
        clubId: "club3",
        otherPaymentMethod: "",
        creator: {
            uid: "creator3",
            userType: "organizer",
            bio: "Passionate about organizing sports events.",
            age: 45,
            email: "organizer@example.com",
            isHidden: false,
            birthDate: "1979-08-30",
            coverPhoto: "/static/cover3.jpg",
            mainProfilePhoto: "/static/profile3.jpg",
            userPhotos: [],
            userInterests: ["tennis", "volunteering"],
            name: "George Martin",
            gender: "Male",
            blockedUsers: [],
            joinedActivities: [],
            joinedEvents: [],
            joinedTrips: [],
            bookmarkedEvents: [],
            bookmarkedActivities: [],
            bookmarkedTrips: [],
            isProfileVerified: true,
            isEmailVerified: true,
            instagram: "tennis_events",
            tikTok: "",
            website: "https://sportsorganizer.com",
            link: "",
            youTube: "",
            fcmToken: ["token123"],
            reviewCount: 20,
            nationality: "British",
            nationalityCode: "GB",
            connectedAccountId: "account789",
            createdAt: moment().subtract(10, "days").toISOString(),
            lastSignedInAt: moment().subtract(1, "days").toISOString(),
            createdLocation: { type: "Point", coordinates: [51.5074, -0.1278] },
            location: { type: "Point", coordinates: [51.5074, -0.1278] },
            locationString: "London, UK",
            isNotificationsEnabled: true,
            isActivitiesNotificationsEnabled: true,
            isConnectionNotificationsEnabled: true,
            isMessageNotificationsEnabled: true,
        },
        isOnline: false,
    },
    {
        type: "workshop",
        coverPhotoUrl: "/static/event.svg",
        optionalPhotos: [],
        sport: "Yoga",
        title: "Sunrise Yoga Workshop",
        description: "Rejuvenate your body and mind with sunrise yoga.",
        cancelled: false,
        deleted: false,
        participants: ["user11", "user12"],
        participantsLimit: 25,
        isUnlimitedParticipants: false,
        trainingLocationString: "Beachside Yoga Center",
        trainingLocation: { type: "Point", coordinates: [37.7749, -122.4194] },
        trainingStartDateTime: moment().add(10, "days").toISOString(),
        trainingEndDateTime: moment().add(10, "days").add(3, "hours").toISOString(),
        commentCount: 12,
        link: "https://yogaworkshop.com",
        likedBy: ["user12", "user13"],
        createdAt: moment().subtract(4, "days").toISOString(),
        paymentMethods: ["cash", "paypal"],
        price: 15,
        priceCurrency: "USD",
        clubId: "club4",
        otherPaymentMethod: "",
        creator: {
            uid: "creator4",
            userType: "instructor",
            bio: "Certified yoga instructor with 10 years of experience.",
            age: 38,
            email: "instructor@example.com",
            isHidden: false,
            birthDate: "1985-05-22",
            coverPhoto: "/static/cover4.jpg",
            mainProfilePhoto: "/static/profile4.jpg",
            userPhotos: [],
            userInterests: ["yoga", "health"],
            name: "Maya Patel",
            gender: "Female",
            blockedUsers: [],
            joinedActivities: [],
            joinedEvents: [],
            joinedTrips: [],
            bookmarkedEvents: [],
            bookmarkedActivities: [],
            bookmarkedTrips: [],
            isProfileVerified: true,
            isEmailVerified: true,
            instagram: "yogainstructor",
            tikTok: "",
            website: "",
            link: "",
            youTube: "",
            fcmToken: ["token234"],
            reviewCount: 18,
            nationality: "Indian",
            nationalityCode: "IN",
            connectedAccountId: "account456",
            createdAt: moment().subtract(8, "days").toISOString(),
            lastSignedInAt: moment().subtract(2, "days").toISOString(),
            createdLocation: { type: "Point", coordinates: [19.076, 72.8777] },
            location: { type: "Point", coordinates: [19.076, 72.8777] },
            locationString: "Mumbai, India",
            isNotificationsEnabled: true,
            isActivitiesNotificationsEnabled: true,
            isConnectionNotificationsEnabled: true,
            isMessageNotificationsEnabled: true,
        },
        isOnline: true,
    },
    {
        type: "webinar",
        coverPhotoUrl: "/static/event.svg",
        optionalPhotos: [],
        sport: "Fitness",
        title: "Online Fitness Webinar",
        description: "Learn advanced fitness techniques from top trainers.",
        cancelled: false,
        deleted: false,
        participants: ["user14", "user15", "user16"],
        participantsLimit: 100,
        isUnlimitedParticipants: true,
        trainingLocationString: "Online",
        trainingLocation: { type: "Point", coordinates: [37.7749, -122.4194] },
        trainingStartDateTime: moment().add(14, "days").toISOString(),
        trainingEndDateTime: moment().add(14, "days").add(2, "hours").toISOString(),
        commentCount: 25,
        link: "https://fitnesswebinar.com",
        likedBy: ["user15", "user17"],
        createdAt: moment().toISOString(),
        paymentMethods: ["credit card"],
        price: 50,
        priceCurrency: "USD",
        clubId: "club5",
        otherPaymentMethod: "",
        creator: {
            uid: "creator5",
            userType: "trainer",
            bio: "Fitness trainer and motivational speaker.",
            age: 32,
            email: "trainer@example.com",
            isHidden: false,
            birthDate: "1991-11-02",
            coverPhoto: "/static/cover5.jpg",
            mainProfilePhoto: "/static/profile5.jpg",
            userPhotos: [],
            userInterests: ["fitness", "nutrition"],
            name: "Liam Brown",
            gender: "Male",
            blockedUsers: [],
            joinedActivities: [],
            joinedEvents: [],
            joinedTrips: [],
            bookmarkedEvents: [],
            bookmarkedActivities: [],
            bookmarkedTrips: [],
            isProfileVerified: true,
            isEmailVerified: true,
            instagram: "fitwithliam",
            tikTok: "",
            website: "https://fitwithliam.com",
            link: "",
            youTube: "",
            fcmToken: ["token345"],
            reviewCount: 30,
            nationality: "American",
            nationalityCode: "US",
            connectedAccountId: "account567",
            createdAt: moment().subtract(5, "days").toISOString(),
            lastSignedInAt: moment().subtract(1, "days").toISOString(),
            createdLocation: { type: "Point", coordinates: [34.0522, -118.2437] },
            location: { type: "Point", coordinates: [34.0522, -118.2437] },
            locationString: "Los Angeles, USA",
            isNotificationsEnabled: true,
            isActivitiesNotificationsEnabled: true,
            isConnectionNotificationsEnabled: true,
            isMessageNotificationsEnabled: true,
        },
        isOnline: true,
    },
];

const clubs = [
    {
        title: "Running Club",
        rating: 4.5,
        reviews: 23,
        members: 199,
        distance: "4.3 km",
        location: "Barcelona, Spain",
        clubImage: "/static/club-1.svg",
        userImage: "/static/userImagePlaceholder.svg",
    },
    {
        title: "Cycling Club",
        rating: 4.8,
        reviews: 56,
        members: 345,
        distance: "6.2 km",
        location: "Madrid, Spain",
        clubImage: "/static/club-2.svg",
        userImage: "/static/userImagePlaceholder.svg",
    },
    {
        title: "Photography Club",
        rating: 4.6,
        reviews: 78,
        members: 150,
        distance: "2.1 km",
        location: "Valencia, Spain",
        clubImage: "/static/club-3.svg",
        userImage: "/static/userImagePlaceholder.svg",
    },
    {
        title: "Running Club",
        rating: 4.5,
        reviews: 23,
        members: 199,
        distance: "4.3 km",
        location: "Barcelona, Spain",
        clubImage: "/static/club-1.svg",
        userImage: "/static/userImagePlaceholder.svg",
    },
    {
        title: "Cycling Club",
        rating: 4.8,
        reviews: 56,
        members: 345,
        distance: "6.2 km",
        location: "Madrid, Spain",
        clubImage: "/static/club-2.svg",
        userImage: "/static/userImagePlaceholder.svg",
    },
    {
        title: "Photography Club",
        rating: 4.6,
        reviews: 78,
        members: 150,
        distance: "2.1 km",
        location: "Valencia, Spain",
        clubImage: "/static/club-3.svg",
        userImage: "/static/userImagePlaceholder.svg",
    },
];

const categories = [
    "Running",
    "Paddle Surf",
    "Snowboard",
    "Hiking",
    "Mountain Cycling",
    "Yoga",
    "Surf",
    "Fitness",
    "Climbing",
    "Tennis",
    "Parkour",
    "Other",
];

export {
    socials,
    tabs,
    dummyEvents,
    reviewCards,
    clubs,
    categories
};